config/routes.rb
Icanhazblog::Application.routes.draw do

  constraints(:year => /\d{4}/, :month => /\d{2}/) do
    # PS: articles/yyyy/mm/id == articles/id
    get 'articles/:year/:month/:id' => 'articles#show', :as => 'yyyy_mm_article'
    # articles/yyyyy(/mm) -> all articles for given year (and month)
    get 'articles/:year(/:month)' => 'articles#index', :as => 'yyyy_mm_articles'
  end

  resources :articles do
    member do
      post :hide
      post :publish
    end
    
    resources :comments # TODO restrict with :only
  end

  get "log_in" => "sessions#new", :as => "log_in"
  get "log_out" => "sessions#destroy", :as => "log_out"

  resources :sessions, :except => [ :edit ] # TODO restrict with :only

  root :to => "articles#index"

  # Sample of named route:
  #   match 'products/:id/purchase' => 'catalog#purchase', :as => :purchase
  # This route can be invoked with purchase_url(:id => product.id)
  #
  # Sample resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/article.rb
class Article
  include Mongoid::Document
  include Mongoid::Timestamps

  attr_accessible :title, :content, :visible, :tags
  
  field :title
  field :alias

  field :content, :type => String
  field :visible, :type => Boolean, :default => false
  field :published_at, :type => DateTime
  
  embeds_many :comments, :inverse_of => :article
  
  # TODO implement as relational reference?
  field :tags, :type => Array, :default => []

  before_save :update_alias
  
  validates_presence_of :title, :content
  validates_uniqueness_of :title
  validates_length_of :title, :minimum => 3, :maximum => 250

  def year
    self.published_at.year.to_s
  end

  def month
    sprintf("%02d", self.published_at.month)
  end

  def update_alias
    self.alias = self.title.to_s.parameterize
  end
  
  # finds article by its alias (= title.parameterize)
  # wrapper method, also checks if article is visible
  #
  def self.find_by_alias(an_alias)
    self.where(:alias => an_alias, :visible => true).first
  end
    
  # provide public interface for listing and searching articles
  # TODO convert to separate model, ArticleSearch?
  #
  def self.list(params = {})    
    params = self.sanitize_search_params(params)

    # transform :year and :month params to :from and :to params
    # OPTIMIZE why not search by year/month/day indexes instead?
    # TODO deal with incorrect dates that can't be parsed
    if params[:year].present? && (params[:year].to_s =~ /^\d{4}$/)
      if params[:month].present? && (params[:month].to_s =~ /^\d{2}$/)
        date_from = Date.parse("#{params[:year]}/#{params[:month]}/01")
        params[:from] = date_from.to_s
        params[:to] = date_from.end_of_month.to_s
      else
        date_from = Date.parse("#{params[:year]}/01/01")
        params[:from] = date_from.to_s
        params[:to] = date_from.end_of_year.to_s
      end
    end
    
    params[:page] ||= 1
    params[:per_page] ||= 10
    params[:show_hidden] ||= false
    params[:order] ||= "published_at"
    # TODO return errors on invalid dates - after conversion into ArticleSearch model
    params[:from] = (Date.parse(params[:from]) rescue nil) if params[:from]
    params[:to] = (Date.parse(params[:to]) rescue nil) if params[:to]

    q = self
    
    # show only visible articles
    q = q.where(:visible => true) unless params[:show_hidden]
    
    # show only articles for certain date range
    if params[:from] and params[:to]
      q = where(:published_at.gte => params[:from], :published_at.lte => params[:to])
    end
    
    # show only articles which have certain tag
    q = q.where(:tags => params[:tag]) if params[:tag]
    
    # set order
    q = q.descending(params[:order].to_sym)
    
    q.paginate(params)
  end

  # return recently published articles
  #
  def self.recent(nr = 5)
    self.list(:per_page => nr)
  end
  
  # make article visible to users
  def publish!
    self.visible = true
    self.published_at ||= Time.current
    self.save
  end
  
  # hide article from users
  def hide!
    self.visible = false
    self.save
  end
  
  protected
  
  ALLOWED_SEARCH_KEYS = [ :page, :per_page, :tag, :from, :to, :show_hidden, :order, :year, :month ] 
  
  # keep only allowed parameters and symbolize their keys
  #
  def self.sanitize_search_params(params = {})
    params.symbolize_keys.select { |k,v| ALLOWED_SEARCH_KEYS.include?(k) }
  end
  
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  
  before_filter :admin_access_required, :except => [ :index, :show ]

  # GET /articles
  # TODO move admin listing to admin/article controller
  def index
    if admin?
      params[:show_hidden] ||= true
      params[:order] ||= "updated_at"

      @articles = Article.list(params)

      render :template => '/articles/admin_index'
    else      
      # hardcode certain params
      params[:show_hidden] = false
      params[:order] = "published_at"

      @articles = Article.list(params)

      render :action => :index
    end
  end

  # GET /articles/1
  # PS: preferred method to access articles by alias
  def show
    @article = Article.find_by_alias(params[:id]) || Article.find(params[:id])
      rescue raise(ActionController::RoutingError, "Sorry, that article doesn't exist.")

    respond_to do |format|
      format.html # show.html.erb
    end
  end

  # GET /articles/new
  def new
    @article = Article.new

    respond_to do |format|
      format.html
    end
  end

  # GET /articles/1/edit
  def edit
    @article = Article.find(params[:id])
      rescue raise(ActionController::RoutingError, "Sorry, that article doesn't exist.")
  end

  # POST /articles
  def create    
    # TODO move into model as chain-alias method?
    params[:article][:tags] = params[:article][:tags].to_s.split(/[\s,]+/)

    @article = Article.new(params[:article])

    respond_to do |format|
      if @article.save
        format.html { redirect_to(@article, :notice => 'Article was successfully created.') }
      else
        flash.now[:alert] = 'Cannot create the article.'
        format.html { render :action => "new" }
      end
    end
  end

  # PUT /articles/1
  def update
    @article = Article.find(params[:id])
    
    params[:article][:tags] = params[:article][:tags].to_s.split(/[\s,]+/)

    respond_to do |format|
      if @article.update_attributes(params[:article])
        format.html { redirect_to(@article, :notice => 'Article was successfully updated.') }
      else
        flash[:alert] = "Cannot update the article."
        format.html { render :action => "edit" }
      end
    end
  end

  def publish
    @article = Article.find(params[:id])
    @article.publish!
    redirect_to(articles_path, :notice => "Article [#{@article.title}] was published.")
  end
  
  def hide
    @article = Article.find(params[:id])
    @article.hide!
    redirect_to(articles_path, :notice => "Article [#{@article.title}] was hidden.")
  end

  # DELETE /articles/1
  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    flash[:notice] = "The article was deleted."

    respond_to do |format|
      format.html { redirect_to(articles_url) }
    end
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper

  # display list of tags below article
  #  
  def list_of_tags(tags = [])
    return "none" if tags.empty?
    tags.map { |tag_name| search_link_to(tag_name, :tag => tag_name) }.join(", ")
  end

  # display list of all tags with their occurence in blog articles
  # 
  def tag_cloud
    Tag.all.map do |tag_name, tag_occurence|
      search_link_to("#{tag_name} (#{tag_occurence})", { :tag => tag_name }, { :class => "nobr" })
    end.join(", ")
  end
  
  # print information about user above comments
  #
  def user_info(comment)
    if comment.user_nickname.present?
      comment.user_nickname + (comment.user_location ? " (%s)" % comment.user_location : "")
    else
      "anonymous"
    end
  end
  
  # wrapper for articles' content formatting 
  #
  def formatted_text(text)
    raw(coderay(text))
  end
  
  # generate syntax highlighting for <code lang="ruby">...</code> segments
  #
  def coderay(text = "")
    text.gsub(/\<code( lang="(.+?)")?\>\s*(.+?)\<\/code\>/m) do  
      CodeRay.scan($3, $2).div( :css => :class,
        :line_numbers => :inline,
        :tab_width => 2
      )  
    end
  end
  
end

app/views/articles/_form.html.haml
= form_for(@article) do |f|
  - if @article.errors.any?
    #error_explanation
      %h2= pluralize(@article.errors.count, "error") + " prohibited this article from being saved:"

      %ul
        - @article.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :title
    %br
    = f.text_field :title

  .field
    = f.label :content
    %br
    = f.text_area :content

  .field
    = f.label :tags
    %br
    = text_field_tag "article[tags]", @article.tags.join(" ")

  .actions= f.submit

app/views/articles/admin_index.html.haml
#add_article= link_to "Add article", new_article_path

- @articles.each do |article|

  .admin_article_box
    
    .article_published_at= formatted_date article.published_at

    .article_title= link_to article.title, article

    .article_content
      = formatted_text article.content.truncate(200, :separator => " ")

    .article_box_footer

      .comments= "#{article.comments.count} comments"

      .tags
        %span Tags:
        = raw list_of_tags(article.tags)

      .article_actions
        %table
          %tr
            %td
              = button_to "edit", { :action => "edit", :id => article.to_param },
                :method => :get, :class => "article_action"
  
            - if article.visible?
              %td  
                = button_to "hide", { :action => "hide", :id => article.to_param },
                  :method => :post, :class => "article_action"
            - else
              %td
                = button_to "publish", { :action => "publish", :id => article.to_param },
                  :method => :post, :class => "article_action"
  
            %td  
              = button_to "delete", { :action => "destroy", :id => article.to_param },
                :confirm => "Are you sure?", :method => :delete, :class => "article_action"

app/views/articles/edit.html.haml
%h1 Editing article

= render 'form'

= link_to('Show', @article) + " | "
= link_to 'Back', articles_path

app/views/articles/index.html.haml
- @articles.each do |article|

  .article_box
    .article_published_at= formatted_date(article.published_at)

    .article_title= link_to_article(article)

    .article_content= formatted_text(article.content)

    .article_footer

      .comments= raw "#{article.comments.count}&nbsp;comments"
      
      .tags
        %span Tags:
        = raw list_of_tags(article.tags)

app/views/articles/new.html.haml
%h1 New article

= render 'form'

= link_to 'Back', articles_path

app/views/articles/show.html.haml
.article_box
  .article_published_at= formatted_date @article.published_at

  .article_title= @article.title

  .article_content= formatted_text(@article.content)

  .tags
    %span.title Tags:
    = raw list_of_tags(@article.tags)

  #article_comments
    .section_title Comments:

    - @article.comments.each do |comment|
      .comment
        .header
          .title= comment.title
            
          .author
            = "Posted by "
            %span.info= user_info(comment)
            = " at "
            %span.published_at= formatted_date comment.created_at

        .content= comment.content
        
        %div
          - if current_user.try(:admin?)
            = link_to("delete", [ @article, comment ], :confirm => "Are you sure?", :method => :delete)

  = form_for :comment, :url => article_comments_path(@article) do |form|
  
    = form.error_messages
  
    #article_new_comment
      .section_title Add your comment:
    
      - if current_user
        .field= current_user.nickname
      - else
        .field
          = form.label :user_nickname, "What's your name?"
          %br
          = form.text_field :user_nickname

        .field
          = form.label(:user_location, "Where are you from?") + " (optional)"
          %br
          = form.text_field :user_location

      .field
        = form.label :title, "Comment title "
        %br
        = form.text_field :title

      .field
        = form.label :content, "Comment text"
        %br
        = form.text_area :content, :cols => 30, :rows => 4
      
      .field= recaptcha_tags
      
      .actions= form.submit :value => "Add comment"