config/routes.rb
Icanhazblog::Application.routes.draw do

  constraints(:year => /\d{4}/, :month => /\d{2}/) do
    # PS: articles/yyyy/mm/id == articles/id
    get 'articles/:year/:month/:id' => 'articles#show', :as => 'yyyy_mm_article'
    # articles/yyyyy(/mm) -> all articles for given year (and month)
    get 'articles/:year(/:month)' => 'articles#index', :as => 'yyyy_mm_articles'
  end

  resources :articles do
    member do
      post :hide
      post :publish
    end
    
    resources :comments # TODO restrict with :only
  end

  get "log_in" => "sessions#new", :as => "log_in"
  get "log_out" => "sessions#destroy", :as => "log_out"

  resources :sessions, :except => [ :edit ] # TODO restrict with :only

  root :to => "articles#index"

  # Sample of named route:
  #   match 'products/:id/purchase' => 'catalog#purchase', :as => :purchase
  # This route can be invoked with purchase_url(:id => product.id)
  #
  # Sample resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/views/layouts/_date_range_menu.html.haml
#date_range_menu
  .title Date Range

  .content
    = link_to("this month", yyyy_mm_articles_path( :year => Date.current.year,
      :month => sprintf("%02d", Date.current.month) )) + "," 
    = link_to("last month", yyyy_mm_articles_path( :year => 1.month.ago.year,
      :month => sprintf("%02d", 1.month.ago.month) ))

app/views/layouts/_recent_articles.html.haml
#recent_articles_menu
    .title Recent Articles
    
    .content_list
        %ul
            - Article.recent.each do |article|
                %li= link_to_article(article, :title => article.title.truncate(30))

app/views/layouts/_recent_posts.html.erb
<p><strong>Recent Articles</strong></p>
<ul>
    <% Article.recent.each do |article| %>
      <li><%= link_to article.title.truncate(30), article %></li>
    <% end %>
</ul>

app/views/layouts/_tags_menu.html.haml
#tags_menu
  .title Tags

  .content
    = raw tag_cloud()

app/views/layouts/_twitter_stream.html.haml
#twitter_stream_box
  :javascript
    new TWTR.Widget({
      version: 2,
      type: 'profile',
      rpp: 5,
      interval: 6000,
      width: 200,
      height: 300,
      theme: {
        shell: {
          background: '#eeeeee',
          color: '#000000'
        },
        tweets: {
          background: '#555555',
          color: '#eeeeee',
          links: '#eeab00'
        }
      },
      features: {
        scrollbar: false,
        loop: false,
        live: false,
        hashtags: true,
        timestamp: true,
        avatars: false,
        behavior: 'all'
      }
    }).render().setUser('lstejskal').start();

app/views/layouts/application.html.haml
!!! Strict

%html
  %head
    %title Ruby, Rails and all that code
    = stylesheet_link_tag "application"
    = javascript_include_tag "application", "http://widgets.twimg.com/j/2/widget.js"
    = csrf_meta_tag
    %meta{ "http-equiv" => "content-type", :content => "text/html; charset=utf-8" }
  %body
    #container

      - flash.each do |name, msg|
        %div.flash{:id => name}= msg
        
      - if current_user
        #admin_menu
          = "Logged in as %s" % current_user.nickname
          = link_to "Log out", log_out_path
  
      #header
        %h1= link_to "Ruby, Rails And All That Code", root_path
        %h2 by Lukas Stejskal
  
      #wrapper
        #content
        
          = yield
  
      #navigation
      
        = render :partial => "layouts/recent_articles"
      
        .menu_separator &nbsp
      
        = render :partial => "layouts/tags_menu"
  
        .menu_separator &nbsp;
    
        = render :partial => "layouts/date_range_menu"
  
        .menu_separator &nbsp;
    
        = render :partial => "layouts/twitter_stream"
      
      #footer
        %p &copy; 2011 Lukas Stejskal